# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - '*' 

resources:
  repositories:
  - repository: AzurePipelineTemplate #identifier
    type: github # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=example#resources-repositories
    name:  proptree-my/devops-pipeline-template # full path to repo, including name
    endpoint: proptree-my # to be set in project setting
    ref: refs/heads/main # branch

stages:
- template: lambda-serverless-pipeline.yml@AzurePipelineTemplate
